version: '3.4'

services:
  local-postgresql:
    image: postgres:13
    volumes:
      - ./../postgresql/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=local
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5429:5432